name:                transitive-closures
version:             0.1.0.0
github:              "junkidesu/transitive-closures"
license:             BSD-3-Clause
author:              "Anvar Sheryatullayev"
maintainer:          "alvaro.sh03@gmail.com"
copyright:           "2024 Anvar Sheryatullayev"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/junkidesu/transitive-closures#readme>

dependencies:
- base >= 4.7 && < 5
- matrix
- vector
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  transitive-closures-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - transitive-closures

